SELECT * FROM bt1.[CRMD_ORDERADM_H]
WHERE PROCESS_TYPE = 'ZOAV'


SELECT ZZFLD0000AT, coh.GUID, zoh.[BAVMONTHINC] 
FROM bt1.CRMD_OPPORT_H coh WITH(NOLOCK)
INNER JOIN bt1.ZCRMD_ORDERADM_H zoh  WITH (NOLOCK) ON zoh.GUID = coh.GUID 
WHERE ZZFLD0000AT != '' --'2010007454071'